# some nerd font is required to see all the characters
# and glyphs properly: https://starship.rs/guide/#prerequisites

# https://en.wikipedia.org/wiki/box-drawing_character
# https://en.wikipedia.org/wiki/arrow_(symbol)

# first line/row: info & status
[line_break]
disabled = false 

# first param â”€â”Œ
[username]
format = "[ Dyllon]($style) "
style_user = "#FFB266"
style_root = "bold red"
show_always = true

# second param
[hostname]
format = "[$hostname]($style) in "
style = "bold dimmed blue"
trim_at = "-"
ssh_only = false
disabled = true 

# third param â€¦
[directory]
truncation_length = 0
truncate_to_repo = true
truncation_symbol = ""

# before all the version info (python, nodejs, php, etc.)
[git_status]
style = "white"
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
deleted = "x"

[memory_usage]
threshold = 75 
format = "via [${ram}]($style) "
style = "bold dimmed white"
disabled = false

# last param in the first line/row
[cmd_duration]
min_time = 10_000  # show command duration over 10,000 milliseconds (=10 sec)
format = "took [$duration]($style)"
disabled = false

# second line/row: prompt
#
# somethere at the beginning
[battery]
full_symbol = "ï•¸ "
charging_symbol = "ï–ƒ "
discharging_symbol = "ï–‚ "

# prompt: optional param 1
[time]
format = " ğŸ•™ $time($style)\n"
time_format = "%t"
style = "bright-white"
disabled = true

# prompt: param 2 â””â”€
[character]
success_symbol = "\n[â”€âœ](bold green)"
error_symbol = "\n[â”€](bold red)[Ã—](bold red)"

[gcloud]
disabled = true

# symbols

[aws]
symbol = "îŒ½ "

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[git_branch]
symbol = "ï˜ "

[golang]
symbol = "î˜§ "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
symbol = "î‰ "

[package]
symbol = "ï£– "

[perl]
symbol = "î© "

[php]
symbol = "î˜ˆ "

[python]
symbol = "î˜† "

[ruby]
symbol = "îˆ¾ "

[rust]
symbol = "î¨ "

[swift]
symbol = "ï¯£ "


